@MovieApi_HostAddress = https://localhost:5000

# Get all movies
GET {{MovieApi_HostAddress}}/api/movies
Accept: application/json

###

# Get a movie by ID
GET {{MovieApi_HostAddress}}/api/movies/{id:guid}
Accept: application/json

###

# Create a new movie
POST {{MovieApi_HostAddress}}/api/movies
Content-Type: application/json

{
  "title": "Inception",
  "genre": ["Sci-Fi", "Thriller"],
  "releaseDate": "2010-07-16"
}

###

# Update an existing movie
PUT {{MovieApi_HostAddress}}/api/movies/{id:guid}
Content-Type: application/json

{
  "title": "Inception Updated",
  "genre": ["Sci-Fi"],
  "releaseDate": "2010-07-16"
}

###

# Delete a movie
DELETE {{MovieApi_HostAddress}}/api/movies/{id:guid}

###